### PR TITLE
Bugfix: Update docker-compose.yml

### PR DESCRIPTION
**Pull request by werk21**
Use "postgres-data" instead of "postgres-data-dev" for volume in service postgres.

### CODE REVIEW

**Comment by Amanb1145** [comment]
Hey I was trying to setup scalelite and also noticed this bug but fixed it myself however when running- `./init-letsencrypt.sh` I am getting this error-
`nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/scalelite.somedomain/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/scalelite.somedomain/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

**Comment by Cristhianbh98** [comment]
Hey @Amanb1145 do you get any news about this? I have the same error in a server with scalelite already running. The ssl encrypt did not renovate.

**Comment by Amanb1145** [comment]
Hey Christian,
No news yet. I tried to ask on BBB google group also but no response.

**Comment by Cristhianbh98** [comment]
Hey
I could resolve the issue generating the cert manually and then paste in /data/certbot/conf/live/.
This post in github explain it. [link](https://github.com/blindsidenetworks/scalelite/issues/1015)
But if you need the code I used, i used this docker-compose.yml file

```
version: '3.1'
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=yourdomain.com
      - SUBDOMAINS=
      - VALIDATION=http
      - EMAIL=youremail@example.com
    volumes:
      - ./config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
```

replace the EMAIL and URL with your email and URL, also the cert will be generate in the folder /config/ that is mapped with the volume in docker.

**Review by jfederico — APPROVED** [review]

**Pull request merged**
