### PR TITLE
Add non-interactive script options and fix nginx container name

### PR DESCRIPTION
**Pull request by tezvi**
Hi Federico!

Figured out some thing to improve so I'll give it a go :)
This PR will introduce script options for non-interactive mode. It is useful when script is executed by crontab or from a non-interactive shell. When using non-interactive mode script will not ask for any user input.

Additionally, Nginx container name was hardcoded even though a different name was defined in docker-composer.yml. Script will now detect proper name from docker-compose file.

### CODE REVIEW

**Comment by philou511** [comment]
Replacing scalelite-nginx with scalelite-proxy in the init-letsencrypt.sh script did the job for me (I think at least this should be modified in the .sh script since for now it doesn't seem compatible with the docker-compose.yml file (in which the container is caled scalelite-proxy)
Thank you for scalelite-run : great job :)

**Comment by tezvi** [comment]
This PR resolves naming problem by introducing ENV variable where you can define whatever container name you want.

Unfortunately this repo seems to be abandoned.
However massive thanks to jfederico for initial commit and help with everything.

**Comment by jfederico** [comment]
> Replacing scalelite-nginx with scalelite-proxy in the init-letsencrypt.sh script did the job for me (I think at least this should be modified in the .sh script since for now it doesn't seem compatible with the docker-compose.yml file (in which the container is caled scalelite-proxy) Thank you for scalelite-run : great job :)

Yes, I don't come back here very often since I have many versions of this one. But [PR#14](https://github.com/jfederico/scalelite-run/pull/14) was just merged to address the renaming issue. 

For this case this is the way to go as we want people to use consistent names of the containers, so we can respond questions more easily.

**Comment by jfederico** [comment]
> This PR resolves naming problem by introducing ENV variable where you can define whatever container name you want.
> 
> Unfortunately this repo seems to be abandoned. However massive thanks to jfederico for initial commit and help with everything.

Yeah, sorry @tezvi I have been busy dealing with Scalelite issues themselves :D

Thanks for the PR though. I am glad people still finds it useful.

I have to bring it up to date. We are intending to change the "official" supported deployment from systemd to this. Hopefully you will find these scripts and good documentation inside the main repo soon.

**Pull request merged**
